# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47ef5139040017d43c21a1bf7762289a650a9a70751100848878c27ef62844d6b4ce37e8751a78d00dabfe691771a2bea5d1b795a2e9000055c4d80da9ec6fac

test:
  secret_key_base: 91f2cf19bce6707e41290e350f41c741ab2d9e041927d1d9cc02fa3b410c5aadee092be6deea8b94f83f4f463c1173447065a15d7f31b15b39628977f1906cab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
